### ISSUE TITLE
Proposal: ability to specify subdirectory containing vim plugin

### ISSUE THREAD

**Issue by rcoconnor** [savq/paq-nvim#54] opened 2021-07-19 13:10 UTC
Some color schemes have their vim plugins within a subdirectory of the repo. For instance, vim plug has the rtp option, which allows you to specify the subdirectory containing the vim plugin.

**Comment by bR3iN** [comment] 2021-07-21 15:26
This seems to be a duplicate of #10.

**Comment by nanozuki** [comment] 2021-08-17 03:18
> This seems to be a duplicate of #10.

I read #10, but I found another method for this, maybe also work in Windows?

https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository/52269934#52269934

**Comment by savq** [comment] 2023-08-03 20:42
Duplicate of #10

**Closed by savq** 2023-08-03 20:42 UTC

**Comment by gwerbin** [comment] 2023-12-25 05:04
I figured out a workaround for this that works for my use cases.

First, install the main repository with some `as =` alias, then symlink or copy/install the desired subdirectory to the desired location using `build =`. Example:

```lua
require("paq") {

p {"vlime/vlime", as = "_vlime", build = "ln -fnrs vim ../vlime"}

}
```

You could use `install` or `rsync` here instead of `ln`, as desired.

(I know that this isn't actually necessary for Vlime anymore, but it's the first example I came up with).
